#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
email = "m@tembbo.com"
name = "tembbo"

[signing]
backend = "gpg"
behavior = "own"

[aliases]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'

[ui]
default-command = "log"
